# syntax=docker/dockerfile:1
ARG RUBY_VERSION=3.4.5
FROM ruby:$RUBY_VERSION-slim AS base

# Install base OS dependencies
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential \
    git \
    curl \
    libjemalloc2 \
    libvips \
    libyaml-dev \
    pkg-config && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Set correct environment
ENV RAILS_ENV=development \
    BUNDLE_PATH=/bundle \
    BUNDLE_BIN=/bundle/bin \
    GEM_HOME=/bundle \
    PATH=/bundle/bin:$PATH \
    BUNDLER_VERSION=2.6.9

# Install correct bundler version
RUN gem install bundler -v ${BUNDLER_VERSION}

# Copy Gemfiles and install gems
WORKDIR /app
COPY . ./
RUN bundle _${BUNDLER_VERSION}_ install

# Precompile bootsnap (optional)
# RUN bundle exec bootsnap precompile app/ lib/
# RUN bin/rails assets:precompile

# Expose Rails default port

EXPOSE 3000

# Use bin/dev ONLY for a dev container NOT live.
CMD [ "bin/dev" ]
